apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80         # Puerto de acceso externo
      targetPort: 8080 # Puerto interno en el contenedor
      nodePort: 30080  # Puerto de acceso externo en el rango 30000-32767
  type: NodePort
